### ISSUE TITLE
Was it intentional to hide the http response status from the error formatter?

### ISSUE THREAD

**Issue by drewnichols** [ruby-grape/grape#2527]
I'm curious if this was discussed before and done intentionally. 

For some reason, the `status` value is not passed into the `format_message` method here in `error!`:

https://github.com/ruby-grape/grape/blob/5ce44def9ce7026ad140a31a146820d081ab6798/lib/grape/middleware/error.rb#L132-L137

Passing it would make including it in the response body JSON easier. This is the way it's included in the [JSON API error response bodies](https://jsonapi.org/examples/#error-objects):

```yaml
# HTTP/1.1 422 Unprocessable Entity
# Content-Type: application/vnd.api+json

{
  "errors": [
    {
      "status": "422",
      "source": { "pointer": "/data/attributes/firstName" },
      "title":  "Invalid Attribute",
      "detail": "First name must contain at least two characters."
    }
  ]
}
```
