### ISSUE TITLE
restric access json data with grape and rails 3

### ISSUE THREAD

**Issue by hyperrjas** [ruby-grape/grape#367]
I have a json data in this address:

```
http://localhost:3000/api/v1/apisearch
```

These json data are generated with grape gem:

```
class API_v1 < Grape::API
  version 'v1', :using => :path, :vendor => 'myapp', :format => :json
    get :apisearch do
      Object.search({query: "*#{params[:q]}*"}).map{ |object| {id: object.title, text: object.description } }
    end
 end
```

I have a search engine that get data from this address with [select2](http://ivaynberg.github.com/select2/)

This is my coffescript file:

```
jQuery ->
  $('#query_txt').select2
    width: 'resolve'
    allowClear: true
    minimumInputLength: 2
    ajax:
      url: "api/v1/apisearch"
      dataType: 'json'
      data: (term, page) -> {q: term}
      results: (data, page) ->
        results: data
```

The script is working very fine, but I would like protect this address of external requests.

I don't want to allow a user if type `http://localhost:3000/api/v1/apisearch` can access to these data. Only can access to these data my internal search engine from my own application.

**How can I restric access data only to my own application from grape?**

Thank you
